### ISSUE TITLE
more SYSREFs to FPGA

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_RTM#35]
Right now there is only one SYSREF (and it seems to be not even properly connected).
Ideally, we want two SYSREFs on each FPGA (RTM and AMC). See here:
https://github.com/sinara-hw/sinara/issues/574#issuecomment-467014358

**Comment by gkasprow** [comment]
I can scrap one GTH clock that goes to the 227 bank.

**Comment by sbourdeauducq** [comment]
Commented in the wrong issue?
This is about the SYSREF signals on the RTM. I believe this is resolved.

**Comment by sbourdeauducq** [comment]
Or you mean, removing a GTH clock to make room for a SYSREF in the AMC/RTM connector?

**Comment by gkasprow** [comment]
Yes. I connected 2 SYSREF signals to the RTM FPGA and only one to AMC FPGA.

**Comment by sbourdeauducq** [comment]
OK in that case yes:
* remove GTH clock to bank 227
* replace with SYSREF that goes into the same bank as the CDR clock (We will try to use DDMTD this time, not simple 125/150 sampling).

**Comment by sbourdeauducq** [comment]
And make sure that the CDR clock goes to a GC.

**Comment by gkasprow** [comment]
OK, the LVDS30 pair is used instead of GT clock
![obraz](https://user-images.githubusercontent.com/4325054/53509850-f9c1c880-3abc-11e9-878d-18997b4b09c0.png)

it is routed to the HMC output from one side
![obraz](https://user-images.githubusercontent.com/4325054/53509882-0e05c580-3abd-11e9-83fb-efc4012d879d.png)

and AMC FPGA input from other side, just about the CDR clock input
![obraz](https://user-images.githubusercontent.com/4325054/53509970-35f52900-3abd-11e9-88b6-f6c88f9834af.png)
