### ISSUE TITLE
dnp active loop filter

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#59]
Maybe it is already DNPd, but that's not shown on the schematics you posted?

**Comment by gkasprow** [comment]
True, The AD crashed at a certain moment and even though all files were saved, the recent variant configuration was lost. Anyway, I'm very happy with AD19 - it crashed only a few times this year while AD17 used to crash a few times per day. The good thing with AD19 is that even with a crash, one loses max 10mins of work. Previous AD versions used to stop doing backups without any warning. 
Mentor tools save schematic after every modification, but PCB needs manual saving because of the automatic one works sometimes.
